modLoader="javafml"
loaderVersion="[34,)"
license="All Rights Reserved"
#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]]
modId="infinity_barrels"
version="${file.jarVersion}"
displayName="Infinity Barrels"
authors="Naxanria"
description='''
Adds infinity barrels. Barrels that contain infinite amount of items.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.infinity_barrels]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinity_barrels]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinity_barrels]]
    modId="wtbw_lib"
    mandatory=true
    versionRange="[2.0.0,)"
    ordering="NONE"
    side="BOTH"
